version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: featureflags-postgres
    environment:
      POSTGRES_DB: featureflags
      POSTGRES_USER: featureflags_user
      POSTGRES_PASSWORD: featureflags_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: featureflags-backend:1.0
    container_name: featureflags-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/featureflags
      DB_USERNAME: featureflags_user
      DB_PASSWORD: featureflags_pass
    restart: unless-stopped

volumes:
  postgres_data:
