version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: featureflags-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: featureflags
      POSTGRES_USER: featureflags_user
      POSTGRES_PASSWORD: featureflags_pass
    command: >
      postgres
      -c max_connections=50
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
